AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "spec/dummy/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "coverage/**/*"

require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "wild.gemspec"
    - "Rakefile"

Metrics/MethodLength:
  Max: 20

Gemspec/DevelopmentDependencies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4
